config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'bookings', to: 'pages#bookings'

  resources :flats do
    resources :bookings, only: [:create, :new]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bookings, only: :destroy do
    member do
      post 'update_status', to: 'bookings#update_status'
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy


  validates :address, :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 50, less_than: 1000 }

  before_validation :set_name_if_blank

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo

  def set_name_if_blank
    self.name = "#{user.username.to_s.capitalize}'s Flat" if name.blank? && user.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: allow-list approach
  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: [:create, :destroy]


  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.flat = @flat
    authorize @booking
    authorize @flat

    if @booking.save!
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to root_path, notice: 'Booking was successfully destroyed!', status: :see_other
  end

  def update_status
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.flat.user == current_user
      if @booking.booking_status == true
        @booking.update(booking_status: false)
      else
        @booking.update(booking_status: true)
      end
      redirect_to bookings_path, notice: 'Booking status updated successfully.'
    else
      redirect_to bookings_path, alert: 'You are not authorized to update this booking.'
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:checkin, :checkout, :people, :flat_id)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:edit, :update, :destroy, :show]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @flats = policy_scope(Flat)
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat}),
        marker_html: render_to_string(partial: "markers")
      }
    end

    if params[:query].present?
      sql_subquery = "name @@ :query OR address @@ :query OR description @@ :query"
      @flats = @flats.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize @flat

    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @flat
    @booking = Booking.new
    authorize @booking
    @flat_array = Flat.where(id: @flat.id)
    @marker = @flat_array.geocoded.map do |flat| {
      lat: flat.latitude,
      lng: flat.longitude,
      marker_html: render_to_string(partial: "markers")
    }
    end
  end

  def edit
    authorize @flat
  end

  def update
    authorize @flat
    @flat.user = current_user
    if @flat.update(flat_params)
      redirect_to flat_path(@flat), notice: 'Upadated successfully!', status: :see_other
    else
      render :edit
    end
  end

  def destroy
    authorize @flat
    @flat.destroy
    redirect_to flats_path, notice: 'Flat was successfully destroyed!', status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :price, :address, :photo)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def bookings
    @bookings = Booking.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "custom-button" %>
  </div>
<% end %>




<%# THIS IS THE FORM FOR BOOKING  %>

<%# <div class="booking-form">
							<form>
								<div class="form-group">
									<span class="form-label">Your Destination</span>
									<input class="form-control" type="text" placeholder="Enter a destination or hotel name">
								</div>
								<div class="row">
									<div class="col-sm-6">
										<div class="form-group">
											<span class="form-label">Check In</span>
											<input class="form-control" type="date" required="">
										</div>
									</div>
									<div class="col-sm-6">
										<div class="form-group">
											<span class="form-label">Check out</span>
											<input class="form-control" type="date" required="">
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-4">
										<div class="form-group">
											<span class="form-label">Rooms</span>
											<select class="form-control">
												<option>1</option>
												<option>2</option>
												<option>3</option>
											</select>
											<span class="select-arrow"></span>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="form-group">
											<span class="form-label">Adults</span>
											<select class="form-control">
												<option>1</option>
												<option>2</option>
												<option>3</option>
											</select>
											<span class="select-arrow"></span>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="form-group">
											<span class="form-label">Children</span>
											<select class="form-control">
												<option>0</option>
												<option>1</option>
												<option>2</option>
											</select>
											<span class="select-arrow"></span>
										</div>
									</div>
								</div>
								<div class="form-btn">
									<button class="submit-btn">Check availability</button>
								</div>
							</form>
						</div> %>

app/views/flats/_info_window.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/flats/_markers.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>New flat</h1>

      <%= render "form", flat: @flat %>

      <br>

      <div>
        <%= link_to "Back to flats", flats_path, class: "btn btn-warning" %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>List of Flats</h1>
      <div style="width: 100%; height: 200px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    <div class="small-btn">
      <%= link_to "New flat", new_flat_path, style: "text-decoration: none; color: white;" if policy(Flat).new? %>
    </div>
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="flat-card">
        <% if flat.photo.attached? %>
          <div class="flat-card-image" style="background-image: url(<%= cl_image_path flat.photo.key %>);"></div>
          <% else %>
          <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60')"></div>
          <% end %>
          <div class="flat-card-content">

              <h4><%= link_to flat.name, flat_path(flat), class: 'flat-card-title' %></h4>
            <% if flat.description && flat.description.length > 120 %>
            <p style="height: 60px; overflow: hidden;"><%= flat.description.first(120)%>...</p>
            <% else  %>
            <p style="height: 60px; overflow: hidden;"><%= flat.description%></p>
            <% end %>
            <div class="flex">
              <div style="height: 60px; overflow: hidden;" class="flex">
                <i class="material-icons me-2">address</i><span><%= flat.address %></span>
              </div>
                <div class="flex">
                <i class="fa-solid fa-euro-sign"></i> <%= flat.price %> per night
                  <%= link_to "More info", flat_path(flat), class: "yellow-btn" %>
              </div>

            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>New flat</h1>

      <%= render "form", flat: @flats_path %>

      <br>

      <div>
        <%= link_to "Back to flats", flats_path, class: "custom-button" %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="info-booking">
    <div class="flat-show-card">

      <% if !@flat.photo.attached? %>
        <%= image_tag "logo.png", height: 300, width: 400, crop: :fill %>
      <% else %>
        <%= cl_image_tag @flat.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>


        <h1><%= @flat.name %></h1>
          <p class="font-weight-bold"><%= @flat.price %>€ per night</p>
        <p class="flat-show-address"><%= @flat.address %></p>

        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      <div class="button-container">
        <% if policy(@flat).edit? %>
          <%= link_to "Edit flat info", edit_flat_path(@flat), class: "custom-button" %>
        <% end %>
        <% if policy(@flat).destroy? %>
        <%= button_to "Delete this flat", @flat, class: "custom-button", method: :delete if policy(@flat).destroy? %>
        <% end %>
        <%= link_to "Back to flats list", flats_path, class: "custom-button" %>
      </div>


      </div>
            <div class="flat-form">

        <% if @flat.user.id == current_user.id %>

          <%= link_to "Go to your Booking Dashboard", bookings_path, class: "custom-button"%>

        <% else %>

          <%= simple_form_for [@flat, @booking] do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs">
             <label for="booking_checkin">Check-in date</label>
            <%= f.input :checkin, as: :date, html5: true, label: false %>

            <label for="booking_checkout">Check-out date</label>
            <%= f.input :checkout, as: :date, html5: true, label: false %>

            <label for="booking_people">Number of people</label>
            <%= f.input :people, label: false %>

            <%= f.hidden_field :redirect_path, value: bookings_path %>
          </div>


            <div class="form-actions">
              <%= f.button :submit, class: "custom-button", value: "Book now!" %>
            </div>
          <% end %>

        <% end %>



      </div>
  </div>
    <div class="map">
       <div style="width: 100%; height: 400px;"
          data-controller="mapshow"
          data-mapshow-marker-value="<%= @marker.to_json %>"
          data-mapshow-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbYms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>


  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/bookings.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3>Hello <%= current_user.username.capitalize %>, Welcome to your booking dashboard! </h3>
      <div class="table-position">
        <h4>Your flat(s):</h4>
        <table>
          <thead>
            <tr>
              <th>Booking Id</th>
              <th>Check-In</th>
              <th>Check-Out</th>
              <th>Renter</th>
              <th>Flat</th>
              <th>Price</th>
              <th>Booking status</th>
              <%# <th>Owner</th> %>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @bookings.each do |booking| %>
              <tr>
                <% if (booking.flat.user.id == current_user.id)  %>
                  <td> <%= booking.id %></td>
                  <td> <%= booking.checkin %></td>
                  <td> <%= booking.checkout %></td>
                  <td> <%= booking.user.username %> </td>
                  <td> <%= link_to booking.flat.name , flat_path(booking.flat.id), class: "btn btn-info"  %></td>
                  <td> <%= booking.flat.price * (Booking.last.checkout - Booking.last.checkin).to_i %></td>

                  <% if booking.booking_status? %>
                    <td> Validated </td>
                  <% else %>
                    <td> Not confirmed </td>
                  <% end %>
                  <%# <td><%= booking.flat.user.id %>
                  <td>
                        <% if booking.booking_status? %>
                          <%= button_to "Cancel Reservation", update_status_booking_path(booking), data: {method: "post"}, class: "btn btn-danger", data: { turbo_confirm: "Are you sure you want to update the booking status?" } %>
                        <% else %>
                          <%= button_to "Confirm Reservation", update_status_booking_path(booking), data: {method: "post"}, class: "btn btn-success", data: { turbo_confirm: "Are you sure you want to update the booking status?" } %>
                        <% end %>


                  </td>
                  <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="table-position">
        <h4>Your booking(s):</h4>
        <table>
          <thead>
            <tr>
              <th>Booking Id</th>
              <th>Check-In</th>
              <th>Check-Out</th>
              <th>Flat</th>
              <th>Price</th>
              <th>Booking status</th>
              <th>Owner</th>
              <%# <th>Action</th> %>
            </tr>
          </thead>

            <% @bookings.each do |booking| %>
              <% if booking.booking_status? %>
                <tbody bgcolor="green">
              <% else %>
                <tbody bgcolor="#FF7659">
              <% end %>
              <tr>
                <% if booking.user.id == current_user.id  %>
                  <td> <%= booking.id %></td>
                  <td> <%= booking.checkin %></td>
                  <td> <%= booking.checkout %></td>
                  <td> <%= link_to booking.flat.name , flat_path(booking.flat.id), class: "btn btn-info"  %></td>
                  <td> <%= booking.flat.price * (Booking.last.checkout - Booking.last.checkin).to_i %></td>

                  <% if booking.booking_status? %>
                    <td> Validated </td>
                  <% else %>
                    <td> Not confirmed </td>
                  <% end %>
                  <td><%= booking.flat.user.username.capitalize %></td>
                  <%# <td>
                    <%= link_to "Delete", booking_path(booking), data: {method: "delete"} if policy(booking).destroy? %>
                  <%# </td>  %>
                  <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="button-container">
        <%= link_to "Refresh", bookings_path, class: "btn button-booking" %>
        <%= link_to "Back to flats list", flats_path, class: "custom-button" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/221808/sky.jpg');">

  <div class="container">
    <h1>Choose your next home! </h1>
    <h1>We provide experience, not just a roof. </h1>
        <% if user_signed_in? %>
          <%= link_to "View All Our Offers",flats_path, class:"btn_all" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path,class:"btn_all" %>
          <%= link_to "Sign Up", new_user_registration_path,class:"btn_all" %>
          <%= link_to "View All Our Offers",flats_path, class:"btn_all" %>
        <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar-bootstrap.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home", "#", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Messages", "#", class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end mt-3 w-auto" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                <%= button_to "logout", destroy_user_session_path, method: :delete  %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color: #e3f2fd;">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <span class="navbar-text text-dark" style="margin-right: 15px;">
          <%= current_user.email %>
        </span>


        <li class="nav-item dropdown ml-3">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end mt-3 w-auto" aria-labelledby="navbarDropdown">
            <%= link_to "My Booking", bookings_path, class: "dropdown-item" %>
            <%= link_to "Edit My Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>